### ISSUE TITLE
Changement du nom de "Macro_to_Batch_onOmero_3D_IJ1_Arguments_runMacro_Arguments.ijm"

### ISSUE THREAD

**Issue by brau-frederic** [GReD-Clermont/omero-toolbox-examples#1]
En cohérence avec le papier où la macro a été nommée : "Macro_to_Batch_onOmero_3D_IJ1_Arguments"

**Comment by ppouchin** [comment]
Done in b141759a791420bb3ed8de83593fb24dbe70861e.
